<?php

/*
 * This file is part of the Chameleon System (https://www.chameleonsystem.com).
 *
 * (c) ESONO AG (https://www.esono.de)
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @deprecated since 6.2.0 - use a proper external tool to measure performance.
 */
class TPkgCmsProfileItem_Group extends AbstractPkgCmsProfilerItem
{
    private $children = array();

    public function &addChild(AbstractPkgCmsProfilerItem $child)
    {
        $this->children[] = $child;
        $this->setEndTime($child->getEndTime());

        return $this->children[count($this->children) - 1];
    }

    /**
     * @param array $children
     *
     * @return $this
     */
    public function setChildren($children)
    {
        $this->children = $children;

        return $this;
    }

    /**
     * @return array
     */
    public function getChildren()
    {
        return $this->children;
    }

    public function render($depth = 0)
    {
        $groupHeader = parent::render($depth);
        if (count($this->children) > 0) {
            $longest = $this->getLongest();
            if (null !== $longest) {
                $longest->setName('[LONGEST] '.$longest->getName());
                $groupHeader .= "\n".$longest->render($depth);
            }
            /** @var AbstractPkgCmsProfilerItem $child */
            foreach ($this->children as $child) {
                $groupHeader .= "\n".$child->render($depth + 1);
            }
        }
        $groupHeader .= "\n\n";

        return $groupHeader;
    }

    public function renderCompact($depth = 0)
    {
        $groupHeader = parent::renderCompact($depth);
        if (count($this->children) > 0) {
            $longest = $this->getLongest();
            if (null !== $longest) {
                $longest->setName('[LONGEST] '.$longest->getName());
                $groupHeader .= "\n".$longest->renderCompact($depth);
            }
            /** @var AbstractPkgCmsProfilerItem $child */
            foreach ($this->children as $child) {
                $groupHeader .= "\n".$child->renderCompact($depth + 1);
            }
            $groupHeader .= "\n\n";
        }

        return $groupHeader;
    }

    public function getName()
    {
        return '[GROUP] '.parent::getName(); // TODO: Change the autogenerated stub
    }

    /**
     * @return AbstractPkgCmsProfilerItem
     */
    public function getLongest()
    {
        reset($this->children);
        /** @var null|AbstractPkgCmsProfilerItem $longest */
        $longest = null;
        /** @var AbstractPkgCmsProfilerItem $child */
        foreach ($this->children as $child) {
            $tmp = $child->getLongest();
            if (null === $longest || $tmp->getRuntime() > $longest->getRuntime()) {
                $longest = $tmp;
            }
        }
        reset($this->children);
        if (null === $longest) {
            return null;
        }

        return clone $longest;
    }
}
