<?php

/*
 * This file is part of the Chameleon System (https://www.chameleonsystem.com).
 *
 * (c) ESONO AG (https://www.esono.de)
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace ChameleonSystem\CoreBundle\RequestType;

/**
 * AssetRequestType defines the type of requests for chameleon_*.css files.
 * If the file already exists, it will be returned by the web server without the application being hit.
 * If the file is not found, the application is called to generate it and save it to disk for future requests.
 *
 * @deprecated since 6.1.6 - to be removed in Chameleon 7.0. This request type should not be necessary in the medium
 * term. The CSS files should not be generated by a web request but only in a separate build process.
 * The request type may only be removed if it is no longer necessary to generate CSS files on
 * production systems (although a migration guide might contain instructions to remove references to the class and
 * handle asset requests in a custom way).
 */
class AssetRequestType extends FrontendRequestType
{
    public function getRequestType()
    {
        return RequestTypeInterface::REQUEST_TYPE_ASSETS;
    }
}
