chameleon_system_autoclasses:
  legacy_table_export:
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/Core'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/Core'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/Core'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\Core
      tables:
      - pkg_run_frontend_action
      - cms_content_box
      - cms_cronjobs
      - cms_export_profiles
      - cms_export_profiles_fields
      - cms_font_image
      - cms_interface_manager
      - cms_interface_manager_parameter
      - cms_ip_whitelist
      - cms_language
      - cms_locals
      - cms_lock
      - cms_message_manager_backend_message
      - cms_message_manager_message
      - cms_message_manager_message_type
      - cms_migration_counter
      - cms_migration_file
      - cms_module
      - cms_record_revision
      - cms_right
      - cms_role
      - cms_smart_url_handler
      - cms_tags
      - cms_tpl_module
      - cms_url_alias
      - cms_user
      - cms_usergroup
      - cms_user_sso
      - data_atomic_lock
      - data_contact_topic
      - data_country
      - t_country
      - data_img_teaser
      - data_mail_profile
      - pkg_cms_captcha
      - pkg_cms_changelog_item
      - pkg_cms_changelog_set
      - pkg_cms_class_manager
      - pkg_cms_class_manager_extension
      - pkg_cms_core_log
      - pkg_cms_core_log_channel
      - pkg_cms_counter
      - pkg_cms_result_cache
      - pkg_cms_routing
      - pkg_cms_text_block
      - pkg_cms_theme
      - pkg_cms_theme_block
      - pkg_cms_theme_block_layout
      - pkg_csv2sql
      - pkg_external_tracker
      - pkg_generic_table_export
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/CoreMenu'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/CoreMenu'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/CoreMenu'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\CoreMenu
      tables:
      - cms_menu_category
      - cms_menu_custom_item
      - cms_menu_item
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/CorePagedef'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/CorePagedef'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/CorePagedef'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\CorePagedef
      tables:
      - cms_master_pagedef
      - cms_master_pagedef_spot
      - cms_master_pagedef_spot_access
      - cms_master_pagedef_spot_parameter
      - cms_tpl_page
      - cms_tpl_page_cms_master_pagedef_spot
      - cms_tree
      - cms_tree_node
      - cms_tpl_module_instance
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/CorePortal'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/CorePortal'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/CorePortal'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\CorePortal
      tables:
      - cms_portal
      - cms_portal_domains
      - cms_portal_navigation
      - cms_portal_system_page
      - cms_division
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/CoreConfig'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/CoreConfig'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/CoreConfig'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\CoreConfig
      tables:
      - cms_config
      - cms_config_cmsmodule_extensions
      - cms_config_parameter
      - cms_config_themes
      - cms_config_imagemagick
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/CoreMedia'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/CoreMedia'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/CoreMedia'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\CoreMedia
      tables:
      - cms_document
      - cms_document_security_hash
      - cms_document_tree
      - cms_media
      - cms_image_crop
      - cms_image_crop_preset
      - cms_filetype
      - cms_media_tree
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/CoreModule'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/CoreModule'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/CoreModule'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\CoreModule
      tables:
      - module_customlist_config
      - module_customlist_config_sortfields
      - module_feedback
      - module_list
      - module_list_cat
      - module_list_config
      - module_text
      - cms_wizard_config
      - cms_wizard_step
    - targetDir: '@ChameleonSystemDataAccessBundle/src/Entity/CoreTableConfiguration'
      configDir: '@ChameleonSystemDataAccessBundle/config/doctrine/CoreTableConfiguration'
      metaConfigDir: '@ChameleonSystemDataAccessBundle/config/autoClass/CoreTableConfiguration'
      namespace: \ChameleonSystem\DataAccessBundle\Entity\CoreTableConfiguration
      tables:
      - cms_tbl_conf
      - cms_tbl_conf_index
      - cms_tbl_conf_restrictions
      - cms_tbl_display_list_fields
      - cms_tbl_display_orderfields
      - cms_tbl_extension
      - cms_tbl_field_tab
      - cms_tbl_list_class
      - cms_field_conf
      - cms_field_type
    - targetDir: '@ChameleonSystemExtranetBundle/Entity'
      configDir: '@ChameleonSystemExtranetBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemExtranetBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\ExtranetBundle\Entity
      tables:
      - data_extranet
      - data_extranet_group
      - data_extranet_module_my_account
      - data_extranet_salutation
      - data_extranet_user
      - data_extranet_user_address
      - data_extranet_user_login_history
      - data_extranet_user_shop_article_history
    - targetDir: '@ChameleonSystemCommentBundle/Entity'
      configDir: '@ChameleonSystemCommentBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemCommentBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\CommentBundle\Entity
      tables:
      - pkg_comment
      - pkg_comment_module_config
      - pkg_comment_type
    - targetDir: '@ChameleonSystemImageHotspotBundle/Entity'
      configDir: '@ChameleonSystemImageHotspotBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemImageHotspotBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\ImageHotspotBundle\Entity
      tables:
      - pkg_image_hotspot
      - pkg_image_hotspot_item
      - pkg_image_hotspot_item_marker
      - pkg_image_hotspot_item_spot
    - targetDir: '@ChameleonSystemMultiModuleBundle/Entity'
      configDir: '@ChameleonSystemMultiModuleBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemMultiModuleBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\MultiModuleBundle\Entity
      tables:
      - pkg_multi_module_module_config
      - pkg_multi_module_set
      - pkg_multi_module_set_item
    - targetDir: '@ChameleonSystemNewsletterBundle/Entity'
      configDir: '@ChameleonSystemNewsletterBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemNewsletterBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\NewsletterBundle\Entity
      tables:
      - pkg_newsletter_campaign
      - pkg_newsletter_confirmation
      - pkg_newsletter_group
      - pkg_newsletter_module_signout_config
      - pkg_newsletter_module_signup_config
      - pkg_newsletter_module_signup_teaser
      - pkg_newsletter_queue
      - pkg_newsletter_robinson
      - pkg_newsletter_user
    - targetDir: '@ChameleonSystemShopAffiliateBundle/Entity'
      configDir: '@ChameleonSystemShopAffiliateBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemShopAffiliateBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\ShopAffiliateBundle\Entity
      tables:
      - pkg_shop_affiliate
      - pkg_shop_affiliate_parameter
    - targetDir: '@ChameleonSystemShopPaymentIPNBundle/Entity'
      configDir: '@ChameleonSystemShopPaymentIPNBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemShopPaymentIPNBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\ShopPaymentIPNBundle\Entity
      tables:
      - pkg_shop_payment_ipn_message
      - pkg_shop_payment_ipn_message_trigger
      - pkg_shop_payment_ipn_status
      - pkg_shop_payment_ipn_trigger
    - targetDir: '@ChameleonSystemShopPaymentTransactionBundle/Entity'
      configDir: '@ChameleonSystemShopPaymentTransactionBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemShopPaymentTransactionBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\ShopPaymentTransactionBundle\Entity
      tables:
      - pkg_shop_payment_transaction
      - pkg_shop_payment_transaction_position
      - pkg_shop_payment_transaction_type
    - targetDir: '@ChameleonSystemShopBundle/Entity/Payment'
      configDir: '@ChameleonSystemShopBundle/Resources/config/doctrine/Payment'
      metaConfigDir: '@ChameleonSystemShopBundle/Resources/config/autoClass/Payment'
      namespace: \ChameleonSystem\ShopBundle\Entity\Payment
      tables:
      - shop_payment_handler
      - shop_payment_handler_group
      - shop_payment_handler_group_config
      - shop_payment_handler_parameter
      - shop_payment_method
    - targetDir: '@ChameleonSystemShopRatingServiceBundle/Entity'
      configDir: '@ChameleonSystemShopRatingServiceBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemShopRatingServiceBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\ShopRatingServiceBundle\Entity
      tables:
      - pkg_shop_rating_service
      - pkg_shop_rating_service_history
      - pkg_shop_rating_service_rating
      - pkg_shop_rating_service_teaser_cnf
      - pkg_shop_rating_service_widget_config
    - targetDir: '@ChameleonSystemShopWishlistBundle/Entity'
      configDir: '@ChameleonSystemShopWishlistBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemShopWishlistBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\ShopWishlistBundle\Entity
      tables:
      - pkg_shop_wishlist
      - pkg_shop_wishlist_article
      - pkg_shop_wishlist_mail_history
      - pkg_shop_wishlist_order_item
    - targetDir: '@ChameleonSystemTrackViewsBundle/Entity'
      configDir: '@ChameleonSystemTrackViewsBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemTrackViewsBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\TrackViewsBundle\Entity
      tables:
      - pkg_track_object
      - pkg_track_object_history
    - targetDir: '@ChameleonSystemShopBundle/Entity/Product'
      configDir: '@ChameleonSystemShopBundle/Resources/config/doctrine/Product'
      metaConfigDir: '@ChameleonSystemShopBundle/Resources/config/autoClass/Product'
      namespace: \ChameleonSystem\ShopBundle\Entity\Product
      tables:
      - shop_article
      - shop_article_catalog_conf
      - shop_article_catalog_conf_default_order
      - shop_article_contributor
      - shop_article_document
      - shop_article_document_type
      - shop_article_group
      - shop_article_image
      - shop_article_image_size
      - shop_article_marker
      - shop_article_preview_image
      - shop_article_review
      - shop_article_stats
      - shop_article_stock
      - shop_article_type
      - shop_attribute
      - shop_attribute_value
      - shop_bundle_article
      - shop_contributor
      - shop_contributor_type
      - shop_manufacturer
      - shop_manufacturer_module_conf
      - shop_stock_message
      - shop_stock_message_trigger
      - shop_unit_of_measurement
      - shop_variant_display_handler
      - shop_variant_set
      - shop_variant_type
      - shop_variant_type_handler
      - shop_variant_type_value
    - targetDir: '@ChameleonSystemShopBundle/Entity/ShopCore'
      configDir: '@ChameleonSystemShopBundle/Resources/config/doctrine/ShopCore'
      metaConfigDir: '@ChameleonSystemShopBundle/Resources/config/autoClass/ShopCore'
      namespace: \ChameleonSystem\ShopBundle\Entity\ShopCore
      tables:
      - shop
      - shop_bank_account
      - shop_category
      - shop_category_tab
      - shop_discount
      - shop_shipping_group
      - shop_shipping_group_handler
      - shop_shipping_type
      - shop_suggest_article_log
      - shop_system_info
      - shop_system_info_module_config
      - shop_system_page
      - shop_wrapping
      - shop_wrapping_card
      - pkg_shop_article_preorder
      - pkg_shop_article_review_module_shop_article_review_configuration
      - pkg_shop_currency
      - pkg_shop_footer_category
      - pkg_shop_listfilter
      - pkg_shop_listfilter_item
      - pkg_shop_listfilter_item_type
      - pkg_shop_listfilter_module_config
      - pkg_shop_primary_navi
      - pkg_shop_statistic_group
      - shop_user_notice_list
      - shop_vat
    - targetDir: '@ChameleonSystemShopBundle/Entity/ProductList'
      configDir: '@ChameleonSystemShopBundle/Resources/config/doctrine/ProductList'
      metaConfigDir: '@ChameleonSystemShopBundle/Resources/config/autoClass/ProductList'
      namespace: \ChameleonSystem\ShopBundle\Entity\ProductList
      tables:
      - shop_module_article_list
      - shop_module_article_list_article
      - shop_module_article_list_filter
      - shop_module_articlelist_orderby
    - targetDir: '@ChameleonSystemShopBundle/Entity/ShopOrder'
      configDir: '@ChameleonSystemShopBundle/Resources/config/doctrine/ShopOrder'
      metaConfigDir: '@ChameleonSystemShopBundle/Resources/config/autoClass/ShopOrder'
      namespace: \ChameleonSystem\ShopBundle\Entity\ShopOrder
      tables:
      - shop_order
      - shop_order_basket
      - shop_order_bundle_article
      - shop_order_discount
      - shop_order_export_log
      - shop_order_item
      - shop_order_payment_method_parameter
      - shop_order_shipping_group_parameter
      - shop_order_status
      - shop_order_status_code
      - shop_order_status_item
      - shop_order_step
      - shop_order_vat
    - targetDir: '@ChameleonSystemSearchBundle/Entity'
      configDir: '@ChameleonSystemSearchBundle/Resources/config/doctrine'
      metaConfigDir: '@ChameleonSystemSearchBundle/Resources/autoClass/doctrine'
      namespace: \ChameleonSystem\SearchBundle\Entity
      tables:
      - shop_search_cache
      - shop_search_cache_item
      - shop_search_cloud_word
      - shop_search_field_weight
      - shop_search_ignore_word
      - shop_search_indexer
      - shop_search_keyword_article
      - shop_search_log
      - shop_search_query
    - targetDir: '@ChameleonSystemShopBundle/Entity/ShopVoucher'
      configDir: '@ChameleonSystemShopBundle/Resources/config/doctrine/ShopVoucher'
      metaConfigDir: '@ChameleonSystemShopBundle/Resources/config/autoClass/ShopVoucher'
      namespace: \ChameleonSystem\ShopBundle\Entity\ShopVoucher
      tables:
      - shop_voucher
      - shop_voucher_series
      - shop_voucher_series_sponsor
      - shop_voucher_use
      - shop_user_purchased_voucher