<?php

/*
 * This file is part of the Chameleon System (https://www.chameleonsystem.com).
 *
 * (c) ESONO AG (https://www.esono.de)
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use ChameleonSystem\CoreBundle\MapperLoader\MapperLoaderInterface;
use ChameleonSystem\CoreBundle\RequestType\RequestTypeInterface;
use ChameleonSystem\CoreBundle\Service\RequestInfoServiceInterface;
use ChameleonSystem\CoreBundle\ServiceLocator;
use ChameleonSystem\ViewRendererBundle\objects\interfaces\DataMappingServiceInterface;
use ChameleonSystem\ViewRendererBundle\objects\interfaces\DataMappingServiceResponseInterface;
use ChameleonSystem\ViewRendererBundle\objects\ViewRendererEvent;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

/**
 * View Renderer.
 *
 * example usage:
 *
 *   $oViewRenderer->AddSourceObject("foo", $oFoo);
 *   $oViewRenderer->AddMappers(array(new FooMapper()));
 *   echo $oViewRenderer->Render(dirname(__FILE__) . "/../snippets/foo.html.twig");
 *
 * to use view renderer you'll have to give it source objects (those are your models) and appropriate mappers
 * which map the data from the model to the desired view.
 */
class ViewRenderer
{
    private ?DataMappingServiceInterface $dataMappingService = null;
    private ?DataMappingServiceInterface $mapperChainMappingService = null;
    private bool $showHTMLHints = false;
    private ?DataMappingServiceResponseInterface $dataMappingServiceResponse = null;
    /**
     * @var TPkgViewRendererMapper_ListHandlerData[]
     */
    private array $listMapHandler = [];
    private ?IPkgSnippetRenderer $snippetRenderer = null;
    private ?EventDispatcherInterface $eventDispatcher = null;
    private ?MapperLoaderInterface $mapperLoader = null;
    protected bool $isBackendMode = false;

    /**
     * @var int|null one of \ChameleonSystem\CoreBundle\RequestType\RequestTypeInterface::REQUEST_TYPE_*
     */
    private ?int $oldRequestType = null;

    public function __construct(
        ?DataMappingServiceInterface $dataMappingService = null,
        ?IPkgSnippetRenderer $snippetRenderer = null,
        ?EventDispatcherInterface $eventDispatcher = null,
        ?MapperLoaderInterface $mapperLoader = null)
    {
        $showViewSourceHtmlHints = ServiceLocator::getParameter('chameleon_system_core.debug.show_view_source_html_hints');
        $this->showHTMLHints = ($showViewSourceHtmlHints && _DEVELOPMENT_MODE);
        $this->dataMappingService = $dataMappingService;

        if (null === $this->dataMappingService) {
            $this->dataMappingService = ServiceLocator::get('chameleon_system_view_renderer.data_mapping_service');
        }

        $this->mapperChainMappingService = clone $this->dataMappingService;
        $this->snippetRenderer = $snippetRenderer;

        if (null === $this->snippetRenderer) {
            $this->snippetRenderer = ServiceLocator::get('chameleon_system_snippet_renderer.snippet_renderer');
        }

        $this->eventDispatcher = $eventDispatcher;
        if (null === $this->eventDispatcher) {
            $this->eventDispatcher = ServiceLocator::get('event_dispatcher');
        }
        $this->mapperLoader = $mapperLoader;
        if (null === $this->mapperLoader) {
            $this->mapperLoader = ServiceLocator::get('chameleon_system_core.mapper_loader');
        }
    }

    /**
     * @param string $mapperChainName
     *
     * @return void
     */
    public function addMapperChain($mapperChainName, array $mapperIdentifiers)
    {
        $mapperService = clone $this->mapperChainMappingService;
        $mapperList = [];
        foreach ($mapperIdentifiers as $identifier) {
            $mapperList[] = $this->mapperLoader->getMapper($identifier);
        }
        $mapperService->addMappers($mapperList);
        $this->dataMappingService->addMappingService($mapperChainName, $mapperService);
    }

    /**
     * the mapper cache trigger generated by the render method.
     *
     * @return array|null
     */
    public function getPostRenderMapperCacheTrigger()
    {
        return (null !== $this->dataMappingServiceResponse) ? $this->dataMappingServiceResponse->getCacheTrigger() : [];
    }

    /**
     * @param array $aMappers
     *
     * @return void
     */
    public function AddMappers($aMappers)
    {
        $this->dataMappingService->addMappers($aMappers);
    }

    /**
     * @param array<string, string>|null $transformations
     * @param string|null $mapToArray
     *
     * @return void
     */
    public function AddMapper(IViewMapper $oMapper, $transformations = null, $mapToArray = null)
    {
        $this->dataMappingService->addMapper($oMapper, $transformations, $mapToArray);
    }

    /**
     * Adds a mapper by either its service ID or fully qualified class name.
     *
     * @param string $identifier
     * @param array<string, string>|null $transformations
     * @param string|null $mapToArray
     *
     * @return void
     *
     * @throws LogicException if no service could be found for the passed identifier
     */
    public function addMapperFromIdentifier($identifier, ?array $transformations = null, $mapToArray = null)
    {
        $this->AddMapper($this->mapperLoader->getMapper($identifier), $transformations, $mapToArray);
    }

    /**
     * @param string $key
     *
     * @return ViewRenderer
     */
    public function AddSourceObject($key, $value)
    {
        $this->dataMappingService->addSourceObject($key, $value);

        return $this;
    }

    /**
     * add all SourceObjects from array (use for traditional data arrays).
     *
     * @param array $aVars
     *
     * @return void
     */
    public function AddSourceObjectsFromArray($aVars)
    {
        $this->dataMappingService->addSourceObjectsFromArray($aVars);
    }

    /**
     * generate an array of strings as source.
     *
     * @param string $sTargetName - the array will have this name
     * @param string $sSourceListName - the data is generated from this list
     * @param string $sSourceItemName - each item in the list will be passed by this name to the snippet used to render each item
     * @param string $sSnippet - the snippet path (relative to the ./snippet folder)
     * @param array $aMapperChain - the mapper chain used to generate the data for each item in the list
     *
     * @return void
     */
    public function generateSourceObjectForObjectList($sTargetName, $sSourceListName, $sSourceItemName, $sSnippet, $aMapperChain)
    {
        $oListHandlerData = new TPkgViewRendererMapper_ListHandlerData();
        $oListHandlerData->setTargetVariableName($sTargetName)
            ->setSourceVariableName($sSourceListName)
            ->setItemName($sSourceItemName)
            ->setSnippetName($sSnippet)
            ->setMapperChain($aMapperChain);

        $this->listMapHandler[$sTargetName] = $oListHandlerData;
    }

    /**
     * @param string $sView the path to the view
     * @param IPkgSnippetRenderer|null $oSnippetRenderer used to inject a renderer
     * @param bool $bEnableCaching
     *
     * @return string the rendered snippet
     *
     * @throws MapperException
     * @throws TPkgSnippetRenderer_SnippetRenderingException
     */
    public function Render($sView, $oSnippetRenderer = null, $bEnableCaching = true)
    {
        if (null === $oSnippetRenderer) {
            $oSnippetRenderer = clone $this->snippetRenderer;
            $oSnippetRenderer->InitializeSource($sView, IPkgSnippetRenderer::SOURCE_TYPE_FILE);
            $oSnippetRenderer->clear();
        }

        if ($this->hasListMapHandler()) {
            $this->injectListMapHandler();
        }

        foreach ($this->dataMappingService->getSourceData() as $sVarName => $sourceData) {
            $oSnippetRenderer->setVar($sVarName, $sourceData);
        }

        if (true === $this->dataMappingService->hasMappers()) {
            $this->dataMappingServiceResponse = $this->dataMappingService->performTransformation();

            foreach ($this->dataMappingServiceResponse->getMappedData() as $key => $value) {
                $oSnippetRenderer->setVar($key, $value);
            }
        }

        $this->modifyTemporarilyRequestType();
        $renderedContent = $oSnippetRenderer->render();
        $this->restoreTemporarilyRequestType();

        if ($this->getShowHTMLHints()) {
            $mappersUsed = $this->dataMappingService->getMapperNameList();
            $event = new ViewRendererEvent($renderedContent, $mappersUsed, $sView);
            $this->eventDispatcher->dispatch($event, ViewRendererEvent::EVENT_POST_RENDER);
            $renderedContent = $event->getContent();
        }

        return $renderedContent;
    }

    /**
     * @return bool
     */
    protected function getShowHTMLHints()
    {
        return $this->showHTMLHints;
    }

    /**
     * @param bool $bShow
     *
     * @return void
     */
    public function setShowHTMLHints($bShow)
    {
        $this->showHTMLHints = $bShow;
    }

    /**
     * @return bool
     */
    private function hasListMapHandler()
    {
        return count($this->listMapHandler) > 0;
    }

    /**
     * @return void
     */
    private function injectListMapHandler()
    {
        $this->addMapperFromIdentifier('chameleon_system_view_renderer.mapper.list_handler');
        $this->AddSourceObject(TPkgViewRendererMapper_ListHandler::SOURCE_DATA_INPUT, $this->dataMappingService->getSourceData());
        $this->AddSourceObject(TPkgViewRendererMapper_ListHandler::SOURCE_DATA_NAME, $this->listMapHandler);
    }

    public function isBackendMode(): bool
    {
        return $this->isBackendMode;
    }

    public function setIsBackendMode(bool $isBackendMode = true): void
    {
        $this->isBackendMode = $isBackendMode;
    }

    protected function modifyTemporarilyRequestType(): void
    {
        if (false === $this->isBackendMode()) {
            $this->oldRequestType = null;

            return;
        }

        $this->oldRequestType = $this->getRequestInfoService()->getChameleonRequestType();
        $this->getRequestInfoService()->setChameleonRequestType(RequestTypeInterface::REQUEST_TYPE_BACKEND);
    }

    protected function restoreTemporarilyRequestType(): void
    {
        if (false === $this->isBackendMode() || null === $this->oldRequestType) {
            return;
        }

        $this->getRequestInfoService()->setChameleonRequestType($this->oldRequestType);
    }

    protected function getRequestInfoService(): RequestInfoServiceInterface
    {
        return ServiceLocator::get('chameleon_system_core.request_info_service');
    }
}
